export let jadav = [
    {
        id:1,
        name:"hiii",
        email:"lkjadsfk",
        phone:"65198"
    },
    {
        id:2,
        name:"asf",
        email:"mlm,",
        phone:"9854"
    },
    {
        id:3,
        name:"jpk",
        email:"lovgjn",
        phone:"884894"
    }
]